FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
# Install packages
    apt-get -y --no-install-recommends install \
      # Install Apache
      apache2 \
      # Install required software
      make \
      g++ \
      texlive-base \
      texlive-latex-base \
      gnuplot \
      pari-gp \
      units-filter \
      flex \
      bison \
      perl \
      liburi-perl \
      imagemagick \
      libgd-dev \
      libfl-dev \
      wget \
      curl \
      # Install recommended software
      yacas \
      gap \
      maxima \
      # maxima-share is  needed since we are not installing recommended packages by default
      maxima-share  \
      octave \
      octave-statistics \
      graphviz \
      ldap-utils \
      # scilab never worded for me
      scilab-cli \
      libwebservice-validator-html-w3c-perl \
      qrencode \
      fortune \
      zip \
      unzip \
      libgmp-dev \
      openbabel \
      # Other recommended software
      povray \
      macaulay2 \
      # Install other software
      bc \
      chemeq \
      # Install support for sending email (ssmtp alone is not enough)
      ssmtp \
      bsd-mailx \
      # Install patch
      patch && \
# Enable CGI
    a2enmod cgid && \
# Install support for working behind a reverse proxy
    a2enmod remoteip && \
# This is required to make the default WIMS path for GAP works
    ln -s gap /usr/bin/gap.sh && \
# Configure POVray and Octave according to WIMS instructions
    echo "read+write* = /home/wims/tmp/sessions" >> /etc/povray/3.7/povray.conf && \
# Configure Octave according to WIMS instructions
    # The combination of these two options is weird. A 128k stack seems too small
    # when using the statistics package, and an error is generated by Octave. However,
    # increasing the stack size or removing entirely the option means that WIMS do not
    # recognize Octave anymore when the statistics package is loaded, while works
    # flawlessy otherwise.
    echo "pkg load statistics" >>  /etc/octaverc && \
    echo "-Xss128k" >> /usr/share/octave/6.4.0/m/java/java.opts && \
# Add wims user
    adduser --disabled-password --gecos '' wims

# Compile WIMS
USER wims
WORKDIR /home/wims
COPY patch.txt /home/wims
COPY compile.patch /home/wims
RUN wget https://sourcesup.renater.fr/frs/download.php/file/6702/wims-4.28.tgz && \
    tar xzf wims-4.28.tgz && \
    rm wims-4.28.tgz && \
    patch -p1 < patch.txt && \
    patch < compile.patch && \
    rm patch.txt && \
    rm compile.patch && \
    (yes "" | ./compile --mathjax --jmol --modules --geogebra --shtooka)

# Configure WIMS and entry-point
USER root
COPY entrypoint.sh /
RUN apt-get -y install --no-install-recommends lsb-release && \
    ./bin/setwrapexec && \
    ./bin/setwimsd && \
    ./bin/apache-config && \
    chmod go-rwx ./src && \
    rm -rf /var/lib/apt/lists/* && \
    chmod +x /entrypoint.sh

# Metadata
LABEL maintainer="Gianluca Amato <gianluca.amato.74@gmail.com>"
VOLUME /home/wims/log
VOLUME /home/wims/public_html/modules/devel
ENTRYPOINT [ "/entrypoint.sh" ]
EXPOSE 80/tcp
